export const PRODUCTS = [
  {
    id: 1,
    image: "images/Rectangle 251.png",
    title: "PHILOMENA 22",
    price: "3.90",
    size: "200ft",
  },
  {
    id: 2,
    image: "images/Rectangle 2999.png",
    title: "BOOLEAN EGYPTIAN",
    price: "4.90",
    size: "100ft",
  },
  {
    id: 3,
    image: "images/Rectangle 49.png",
    title: "BLANC",
    price: "3.00",
    size: "150ft",
  },
  {
    id: 4,
    image: "images/Rectangle 55.png",
    title: "BEVERLY",
    price: "2.50",
    size: "90ft",
  },
  {
    id: 5,
    image: "images/Rectangle 52.png",
    title: "ROSEMARY '22",
    price: "4.10",
    size: "200ft",
  },
  {
    id: 6,
    image: "images/Rectangle 48.png",
    title: "ALTERNATING",
    price: "1.90",
    size: "130ft",
  },
  {
    id: 7,
    image: "images/Rectangle 50.png",
    title: "VEIL",
    price: "2.00",
    size: "100ft",
  },
  {
    id: 8,
    image: "images/Rectangle 54.png",
    title: "THE LAWMAKERS",
    price: "2.00",
    size: "120ft",
  },
  {
    id: 9,
    image: "images/Rectangle 53.png",
    title: "ELLIPSIA",
    price: "3.00",
    size: "200ft",
  },
];
